name: Lint Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check . --output-format=github

      - name: Lint with Mypy
        run: |
          pip install mypy
          mypy . --config-file pyproject.toml --ignore-missing-imports --no-namespace-packages
